Update SDK's README to use templated version
shutterstock/public-api-sdk-generator pull request #8
Opened 2019-03-26 18:26 UTC by msmol

2019-03-26 18:55 UTC, timothymcmackin requested changes

2019-03-26 18:55 UTC, timothymcmackin commented on build/sdk/js/templates/README.mustache
> +and set the `SSTK_API_KEY` environment variable. See [here](https://api-reference.shutterstock.com/#oauth).
To run the tests, you must authenticate with the Shutterstock API, get a token, and put the token in the `SHUTTERSTOCK_API_TOKEN` environment variable. See [Authentication](https://api-reference.shutterstock.com/#authentication).

2019-03-26 18:55 UTC, timothymcmackin commented on build/sdk/js/templates/README.mustache
> +$ SSTK_API_KEY="Your API Key"
We've been using `SHUTTERSTOCK_API_TOKEN` everywhere else.

2019-03-27 14:37 UTC, timothymcmackin submitted a review, later dismissed

2019-03-27 18:10 UTC, timothymcmackin commented
@jacobemerick Please review. Is this necessary  to get the generated readme in the root folder of shutterstock/public-api-javascript-sdk?

2019-03-28 14:47 UTC, jacobemerick approved these changes

2019-03-28 15:20 UTC, merged